version: 2
jobs:
  build:
    docker:
      - image: python:3
    steps:
      - checkout
      - run:
          name: Run tests
          command: python setup.py pytest
      - run:
          name: Check typing
          command: |
            pip install . mypy
            mypy airtablemock test --ignore-missing-imports --strict
